# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-01 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='cost',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
